[package]
name = "test-lib"
version = "0.1.0"
edition = "2021"
authors = ["Jürgen Hahn"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
